name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: configure
      run: ./configure

    - name: make
      run: make

    - name: make check
      run: make check

    - name: "Login via Azure CLI"
      run: Azure/login@v1
      with:
        Creds: ${{secrets.AZURE_SECRET}}

    - name: Build Solution (windows)
      run: |
        cd build
        Project1.exe Project1.sln

